Fix dependencies
When doing:

    rosdep install rqt_marble_plugin

Got:

    ERROR: the following packages/stacks could not have their rosdep keys resolved to system dependencies:
    rqt_marble_plugin: Cannot locate rosdep definition for [visualization_marker]

Which I believe you wanted to depend on the markers messages.

Then, to compile, I needed to have installed `libmarble-dev`, so I also added it to the build_depend.

Tested on a ubuntu 12.04 32bit system and it worked.